/* Generated by build_offline.py. Update only after saving an active answer. */
const CACHE='qazaq-offline-cloud-20260911',ASSETS=["app.js", "cloud.js", "config.js", "core.js", "curriculum.js", "dashboard.js", "data.js", "diagnostics.js", "favicon.svg", "firebase-config.js", "fsrs-vendor.js", "icon-192.png", "icon-512.png", "index.html", "knowledge.js", "learning-data.js", "learning-support.js", "learning.js", "lesson-packs.js", "manifest.webmanifest", "microsteps.js", "package-runtime.js", "package-schema.js", "practice-generators.js", "progress.js", "pwa.js", "scheduler.js", "styles.css", "update.html"];
const urls=ASSETS.map(p=>new URL(p,self.registration.scope).href);
self.addEventListener('install',event=>event.waitUntil((async()=>{
 const responses=await Promise.all(urls.map(async url=>{
   const response=await fetch(new Request(url,{cache:'reload',credentials:'same-origin'}));
   if(!response.ok||response.redirected||response.type==='opaque')throw Error('Asset unavailable');
   if(url.endsWith('/index.html')&&!(await response.clone().text()).includes('id="today-view"'))throw Error('Not the trainer');
   return [url,response];
 }));
 const cache=await caches.open(CACHE);await Promise.all(responses.map(([url,response])=>cache.put(url,response)));
 await self.skipWaiting();
})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{
 for(const key of await caches.keys())if(key.startsWith('qazaq-offline-')&&key!==CACHE)await caches.delete(key);
 await self.clients.claim();
})()));
self.addEventListener('message',event=>{if(event.data?.type==='ACTIVATE_UPDATE')self.skipWaiting();});
self.addEventListener('fetch',event=>{
 if(event.request.method!=='GET')return;
 const url=new URL(event.request.url),scope=new URL(self.registration.scope);
 if(url.origin!==scope.origin)return;
 const isHome=event.request.mode==='navigate'&&(url.pathname===scope.pathname||url.pathname===scope.pathname+'index.html');
 const key=isHome?new URL('index.html',scope).href:url.href;
 if(!isHome&&!urls.includes(key))return;
 event.respondWith((async()=>{
  const cache=await caches.open(CACHE);
  try{
    const fresh=await fetch(new Request(event.request,{cache:'reload',credentials:'same-origin'}));
    if(fresh.ok&&!fresh.redirected){await cache.put(key,fresh.clone());return fresh;}
  }catch{}
  return await cache.match(key)||fetch(event.request);
 })());
});
