'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const E=require('./morph-engine.js');
const L=require('./morph-learner-v2.js');
const ui=fs.readFileSync(__dirname+'/morph-ui.js','utf8');
const kitap=E.data.lemmas.find(l=>l.id==='n-кітап');
const formOf=(id,seq)=>E.form(id,seq);
const one=L.explain(kitap,['DAT'],formOf);
assert.equal(one.ok,true);
assert.equal(one.word,E.form('n-кітап',['DAT']).word);
assert.equal(one.steps.length,1);
assert.equal(one.steps[0].meaning,'куда или кому');
const chain=L.explain(kitap,['POSS_3','DAT'],formOf);
assert.equal(chain.ok,true);
assert.equal(chain.word,'кітабына');
assert.equal(chain.steps[0].after,'кітабы');
assert.equal(chain.steps[1].before,'кітабы');
assert.ok(chain.steps[1].why.includes('уже собранного'));
assert.equal(chain.lessonId,'learner.chains.steps');
const unknown=L.resolveLemma('zzzz',E.data.lemmas);
assert.equal(unknown.kind,'unknown');
assert.ok(unknown.message.includes('нет проверенного разбора'));
const transfer=E.data.lemmas.find(l=>l.split==='transfer');
const hidden=L.explain(transfer,['DAT'],()=>{throw new Error('must not build');});
assert.equal(hidden.ok,false);
assert.equal(hidden.kind,'unknown');
const verb=E.data.lemmas.find(l=>l.id==='v-кел');
const bare=L.explain(verb,['AGR_SHORT_1SG'],formOf);
assert.equal(bare.ok,false);
assert.equal(bare.kind,'chain');
assert.ok(bare.message.includes('не поддерживается'));
const visible=JSON.stringify({word:chain.word,steps:chain.steps,note:chain.note,message:hidden.message});
assert.equal(/\b(DAT|LOC|POSS_|COP_|AGR_SHORT|morphState|FSRS)\b/.test(visible),false);
assert.ok(ui.includes('Разобрать форму'));
assert.ok(ui.includes('data-calc-pop'));
assert.ok(ui.includes('Это не считается твоей ошибкой. Расписание повторений не меняется.'));
const calcFn=ui.slice(ui.indexOf('function calculatorScreen'),ui.indexOf('function bindCalculator'));
const calcBind=ui.slice(ui.indexOf('function bindCalculator'),ui.indexOf('function render'));
assert.equal(calcFn.includes('E.answer'),false);
assert.equal(calcFn.includes('recordTeaching'),false);
assert.equal(calcFn.includes('scheduleUpdate'),false);
assert.equal(calcBind.includes('E.answer'),false);
assert.equal(calcBind.includes('recordTeaching'),false);
assert.equal(calcBind.includes('scheduleUpdate'),false);
const next=L.nextMeanings(kitap,[],formOf);
assert.ok(next.some(x=>x.label==='куда или кому'));
assert.equal(next.some(x=>/DAT|POSS_/.test(x.label)),false);
console.log('MORPH_CALCULATOR_OK');
