'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const S=require('./morph-state.js');
const E=require('./morph-engine.js');
const L=require('./morph-learner-v2.js');
assert.equal(S.TEACHING_CONTENT_VERSION,'morph-teaching-20260926-v3');
assert.equal(S.emptyTeaching().contentVersion,'morph-teaching-20260926-v3');
assert.equal(E.data.version,'morph-20260924-v1');
assert.equal(E.bank().length,2231);
const learner=fs.readFileSync('morph-learner-v2.js','utf8');
const ui=fs.readFileSync('morph-ui.js','utf8');
assert.equal(learner.includes('scheduleUpdate'),false);
assert.equal(learner.includes('desired_retention'),false);
assert.equal(learner.includes('data-morph-answer'),false);
assert.ok(ui.includes('data-learner-try'));
const line=ui.split('\n').find(x=>x.includes("querySelectorAll('[data-learner-try]')"));
assert.ok(line);
assert.equal(line.includes('recordTeaching'),false);
assert.equal(line.includes('E.answer('),false);
assert.equal(line.includes('scheduleUpdate'),false);
const html=L.render(L.lessons[0],'full');
assert.ok(html.includes('data-learner-try'));
assert.equal(html.includes('data-morph-answer'),false);
console.log('MORPH_LEARNER_COMPATIBILITY_OK');
