'use strict';
const assert=require('node:assert/strict');
const L=require('./morph-learner-v2.js');
const dat=L.lessons.find(x=>x.id==='learner.dat.kuda');
const poss=L.lessons.find(x=>x.id==='learner.poss.owner');
assert.ok(dat&&poss);
assert.deepEqual(dat.families,['DAT']);
assert.deepEqual(poss.families,['POSS_1SG','POSS_2SG','POSS_1PL','POSS_2POL','POSS_3']);
const datTable=dat.blocks.find(b=>b.id==='dat.7');
const contrast=dat.blocks.find(b=>b.id==='dat.42');
const voice=dat.blocks.find(b=>b.id==='dat.28');
assert.equal(datTable.rows.length,3);
assert.equal(contrast.rows.length,3);
assert.equal(voice.rows.length,5);
const five=poss.blocks.find(b=>b.id==='poss.28');
const after=poss.blocks.find(b=>b.id==='poss.60');
assert.equal(five.rows.length,5);
assert.equal(after.rows.length,4);
for(const id of ['poss.44','poss.45','poss.46','poss.47','poss.49','poss.65','poss.73'])assert.ok(poss.blocks.some(b=>b.id===id),id);
const full=L.visibleText(poss,'full');
assert.ok(full.includes('принципі'));
assert.ok(full.includes('орында'));
assert.ok(full.includes('ерні'));
assert.ok(full.includes('балама'));
assert.ok(full.includes('үйіңе'));
assert.ok(L.visibleText(dat,'full').includes('адаммен'));
const loc=L.lessons.find(x=>x.id==='learner.loc.where');
const pl=L.lessons.find(x=>x.id==='learner.pl.several');
const nasal=L.lessons.find(x=>x.id==='learner.nasal.senses');
assert.equal(loc.blocks.find(b=>b.id==='loc.7').rows.length,3);
assert.equal(loc.blocks.find(b=>b.id==='loc.8').rows.length,3);
assert.equal(pl.blocks.find(b=>b.id==='pl.10').rows.length,7);
assert.equal(nasal.blocks.find(b=>b.id==='nas.3').rows.length,6);
assert.ok(L.visibleText(nasal,'full').includes('адаммын'));
assert.ok(L.visibleText(nasal,'full').includes('адам ба'));
assert.ok(L.visibleText(pl,'full').includes('қарлар'));
assert.ok(L.visibleText(pl,'full').includes('жолдар'));
assert.equal(L.forFamily('harmony','LOC').id,'learner.loc.where');
assert.equal(L.forFamily('voice','LOC').id,'learner.loc.where');
assert.equal(L.forFamily('plural','PL').id,'learner.pl.several');
assert.equal(L.forFamily('nasal','INS').id,'learner.nasal.senses');
assert.equal(L.forFamily('harmony','DAT').id,'learner.dat.kuda');
assert.ok(dat.renderTargets.includes('practice.feedback'));
assert.ok(poss.renderTargets.includes('chains.step'));
console.log('MORPH_LEARNER_COVERAGE_OK');
