'use strict';
const assert=require('node:assert/strict');
const L=require('./morph-learner-v2.js');
const dat=L.lessons.find(x=>x.id==='learner.dat.kuda');
const poss=L.lessons.find(x=>x.id==='learner.poss.owner');
assert.ok(dat&&poss);
assert.deepEqual(dat.families,['DAT']);
assert.deepEqual(poss.families,['POSS_1SG','POSS_2SG','POSS_1PL','POSS_2POL','POSS_3']);
const datTable=dat.blocks.find(b=>b.id==='dat.7');
const contrast=dat.blocks.find(b=>b.id==='dat.42');
const voice=dat.blocks.find(b=>b.id==='dat.28');
assert.equal(datTable.rows.length,3);
assert.equal(contrast.rows.length,3);
assert.equal(voice.rows.length,5);
const five=poss.blocks.find(b=>b.id==='poss.28');
const after=poss.blocks.find(b=>b.id==='poss.60');
assert.equal(five.rows.length,5);
assert.equal(after.rows.length,4);
for(const id of ['poss.44','poss.45','poss.46','poss.47','poss.49','poss.65','poss.73'])assert.ok(poss.blocks.some(b=>b.id===id),id);
const full=L.visibleText(poss,'full');
assert.ok(full.includes('принципі'));
assert.ok(full.includes('орында'));
assert.ok(full.includes('ерні'));
assert.ok(full.includes('балама'));
assert.ok(full.includes('үйіңе'));
assert.ok(L.visibleText(dat,'full').includes('адаммен'));
assert.ok(dat.renderTargets.includes('practice.feedback'));
assert.ok(poss.renderTargets.includes('chains.step'));
console.log('MORPH_LEARNER_COVERAGE_OK');
