'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const L=require('./morph-learner-v2.js');
const E=require('./morph-engine.js');
const ui=fs.readFileSync(__dirname+'/morph-ui.js','utf8');
const trainIds=new Set(E.data.lemmas.filter(l=>l.split==='train').map(l=>l.id));
const transferTexts=E.data.lemmas.filter(l=>l.split==='transfer').map(l=>l.text);
const report=L.check({formOf:(id,seq)=>E.form(id,seq).word,trainIds,transferTexts});
assert.equal(report.ok,true,report.errors.join('\n'));
const nasal=L.lessons.find(x=>x.id==='learner.nasal.senses');
const matrix=nasal.blocks.find(b=>b.id==='nas.49');
assert.equal(matrix.rows.length,7);
assert.equal(matrix.headers.length,10);
assert.deepEqual(matrix.rows[2],['р','л','д','д','д','д','м','м','м','м']);
assert.deepEqual(matrix.rows[4],['м, н или ң','д','н','д','д','н','б','м','б','м']);
assert.deepEqual(matrix.rows[6],['глухой','т','т','т','т','т','п','п','п','п']);
const full=L.visibleText(nasal,'full');
for(const bit of ['қаламмен жазу','күрекпен қазу','-шы само не становится -жы','Семь концов и девять вопросов'])assert.ok(full.includes(bit),bit);
const verbs=L.visibleText(L.lessons.find(x=>x.id==='learner.verbs.steps'),'full');
for(const bit of ['Жаңбыр жауса','не равна одному русскому слову «если»','киініп, шықты','оқып, түсінді','тауып','не «мой предмет»'])assert.ok(verbs.includes(bit),bit);
const pl=L.visibleText(L.lessons.find(x=>x.id==='learner.pl.several'),'full');
assert.ok(pl.includes('Эту таблицу не переноси'));
const fb=L.feedback({stem:'бала',gloss:'ребёнок',expected:'балалар',familyId:'PL',morpheme:'PL',trace:{morpheme:'PL',suffix:'лар'}},['ONSET_CLASS']);
assert.ok(fb.includes('л, д или т'));
assert.ok(fb.includes('не переноси на другой вопрос'));
assert.ok(ui.includes('Он не означает, что тема освоена навсегда.'));
assert.ok(ui.includes('Это не считается твоей ошибкой.'));
const broken=structuredClone(matrix);
broken.rows=broken.rows.slice(0,-1);
assert.notEqual(broken.rows.length,7);
console.log('MORPH_PREMERGE_CONTENT_F1_OK');
