#!/usr/bin/env python3
"""Rebuild the service-worker shell list from the page.

Reads index.html, styles it loads, and the manifest icons.
Writes sw.js ASSETS. Refuses the legacy lesson 4-2 packs and nonpast-engine.js:
those files stay out of the browser. Run from the repo root:

    python tools/build_offline.py --cache qazaq-offline-live-YYYYMMDD-name
    python tools/build_offline.py --check
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SW = ROOT / "sw.js"
# Live 4-2 is the compiled v2 package. These files are node-only leftovers.
LEGACY = (
    "lesson42-pack.js",
    "lesson42-homework.js",
    "lesson-pack-4-2.js",
    "nonpast-engine.js",
)
URL_RE = re.compile(r"""url\(\s*['"]?([^'")]+)['"]?\s*\)""")
IMPORT_RE = re.compile(r"""@import\s+url\(\s*['"]([^'"]+)['"]\s*\)""")


def local_name(raw: str) -> str | None:
    value = raw.strip()
    if not value or value.startswith(("#", "data:", "http:", "https:", "mailto:")):
        return None
    value = value.split("?")[0].split("#")[0]
    if value in ("./", "/"):
        return "index.html"
    return value.lstrip("./")


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def walk_css(name: str, found: list[str], seen: set[str]) -> None:
    if name in seen:
        return
    seen.add(name)
    path = ROOT / name
    if not path.is_file():
        raise SystemExit(f"missing stylesheet {name}")
    text = read(path)
    for raw in IMPORT_RE.findall(text):
        child = local_name(raw)
        if child:
            found.append(child)
            walk_css(child, found, seen)
    for raw in URL_RE.findall(text):
        child = local_name(raw)
        if child and child != name:
            found.append(child)


def collect() -> list[str]:
    html = read(ROOT / "index.html")
    ordered: list[str] = ["index.html"]
    for raw in re.findall(r'(?:src|href)="([^"]+)"', html):
        name = local_name(raw)
        if name:
            ordered.append(name)
    css_seen: set[str] = set()
    css_names = [name for name in ordered if name.endswith(".css")]
    for name in css_names:
        walk_css(name, ordered, css_seen)
    if "manifest.webmanifest" in ordered:
        manifest = json.loads(read(ROOT / "manifest.webmanifest"))
        for icon in manifest.get("icons") or []:
            name = local_name(str(icon.get("src") or ""))
            if name:
                ordered.append(name)
    unique: list[str] = []
    seen: set[str] = set()
    for name in ordered:
        if name in seen:
            continue
        seen.add(name)
        unique.append(name)
    banned = [name for name in unique if name in LEGACY]
    if banned:
        raise SystemExit("page links a file that must stay out of the browser: " + ", ".join(banned))
    missing = [name for name in unique if not (ROOT / name).is_file()]
    if missing:
        raise SystemExit("shell file missing on disk: " + ", ".join(missing))
    return unique


def current_assets(text: str) -> list[str]:
    match = re.search(r"ASSETS=(\[.*?\]);", text)
    if not match:
        raise SystemExit("sw.js has no ASSETS array")
    return json.loads(match.group(1))


def write_sw(assets: list[str], cache: str) -> None:
    text = read(SW).replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(
        r"/\* Generated by build_offline\.py\..*?\*/",
        "/* Generated by tools/build_offline.py. Legacy lesson 4-2 packs and the nonpast engine stay out of this list. */",
        text,
        count=1,
    )
    payload = json.dumps(assets, ensure_ascii=False, separators=(", ", ": "))
    new_line = f"const CACHE='{cache}',ASSETS={payload};"
    text2, count = re.subn(r"const CACHE='[^']*',ASSETS=\[.*?\];", new_line, text, count=1)
    if count != 1:
        raise SystemExit("could not replace the CACHE/ASSETS line")
    SW.write_bytes(text2.encode("utf-8"))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cache", help="new qazaq-offline-live cache name")
    parser.add_argument("--check", action="store_true", help="fail if sw.js drifted from the page")
    args = parser.parse_args()
    assets = collect()
    text = read(SW)
    live = current_assets(text)
    if args.check:
        problems = []
        if set(live) != set(assets):
            extra = sorted(set(live) - set(assets))
            missing = sorted(set(assets) - set(live))
            if extra:
                problems.append("in sw.js only: " + ", ".join(extra))
            if missing:
                problems.append("missing from sw.js: " + ", ".join(missing))
        for name in LEGACY:
            if name in live:
                problems.append("legacy file still cached: " + name)
        if problems:
            print("\n".join(problems))
            return 1
        print(f"offline shell matches the page ({len(assets)} files)")
        return 0
    if not args.cache:
        parser.error("pass --cache when writing sw.js")
    if not re.fullmatch(r"qazaq-offline-live-[0-9]{8}-[a-z0-9-]+", args.cache):
        raise SystemExit("cache name must look like qazaq-offline-live-YYYYMMDD-slug")
    write_sw(assets, args.cache)
    print(f"wrote {len(assets)} assets, cache {args.cache}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
