#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');
const Schema=require('../lesson-v2-schema.js');

const root=path.resolve(__dirname,'..');
const lessonsDir=path.join(root,'lessons');
const dirs=fs.readdirSync(lessonsDir,{withFileTypes:true}).filter(x=>x.isDirectory()).map(x=>x.name).sort((a,b)=>a.localeCompare(b,'en',{numeric:true}));
const compiled=[];
for(const dir of dirs){
  const base=path.join(lessonsDir,dir);
  const lessonPath=path.join(base,'lesson.json');
  if(!fs.existsSync(lessonPath))continue;
  const raw=JSON.parse(fs.readFileSync(lessonPath,'utf8'));
  const sourcesPath=path.join(base,'sources.json');
  const correctionsPath=path.join(base,'corrections.json');
  if(fs.existsSync(sourcesPath))raw.sources=JSON.parse(fs.readFileSync(sourcesPath,'utf8')).sources||[];
  if(fs.existsSync(correctionsPath))raw.corrections=JSON.parse(fs.readFileSync(correctionsPath,'utf8')).corrections||[];
  compiled.push(Schema.validate(raw));
}
const out='/* Generated by tools/compile-lessons.cjs. Do not hand-edit. */\nwindow.LESSON_V2_COMPILED = '+JSON.stringify(compiled,null,2)+';\n';
const target=path.join(root,'compiled-lessons-v2.js');
fs.writeFileSync(target,out,'utf8');
console.log('LESSON_V2_COMPILE_OK',compiled.map(x=>x.lesson_id).join(', '),target);
